""" Written programmatically by Benjamin Jack Cullen """

""" Source and credits to: https://fileinfo.com/ """

font_files = [
    ["font_files",
    ".VLW",
    "Processing Font File",
    "4.3",
    "Font file created by Processing, a program used for making images and animations; saves a collection of glyphs that were converted from another system font (Tools → Create Font in Processing); can be inserted into sketches and animations. Processing can read VLW files using the loadFont() command. Windows Processing. Mac Processing. Linux ProcessingFree.",
    "Windows Processing. Mac Processing. Linux Processing.",
    "?"],
    ["font_files",
    ".JFPROJ",
    "JSON Font Project File",
    "4.1",
    "A JFPROJ file is a font project created by Microsoft Font Maker, a font authoring program for Windows. It contains a font based on the penmanship of a user recorded from a connected electronic pen device. JFPROJ files include the glyphs that make up the alphabet and other symbols, several sentences written by the user, and information about the space between characters and words and the size of the font. You will only encounter a JFPROJ file if you use Microsoft Font Maker for creating fonts. When you save a font, Microsoft Font Maker creates the JFPROJ file to store the information about the font. You can close and re-open the JFPROJ file at a later time to edit it. To create and save a JFPROJ file with Microsoft Font Maker, click the Save icon in the upper-right corner of the program. To open a JFPROJ file with Microsoft Font Maker, click the Open icon in the upper-right corner of the program. When you are done editing a font with Microsoft Font Maker, you can export it as a.TTF file, which can be installed in Windows or macOS and used as a font in various programs, such as Microsoft Word and Adobe Photoshop. NOTE: JFPROJ files store project information in JSON format. Windows Microsoft Font MakerFree.",
    "Windows Microsoft Font Maker.",
    "?"],
    ["font_files",
    ".FNT",
    "Windows Font File",
    "4.0",
    "An FNT file is a font file used by the Windows operating system and often saved within the system fonts directory. It stores a generic font and may include vector and raster glyphs. FNT files have largely been replaced by TrueType (.TTF) and OpenType (.OTF) fonts. Mac FontForge. Windows VSoft FontEdit. FontForge. Microsoft Windows. Linux FontForgeFree. An FNT file is a bitmap font metadata file created by AngelCode Bitmap Font Generator. It contains data used to specify the fonts style and size, as well as extract the fonts characters from associated.DDS,.PNG. or.TGA files. FNT files can be plain text, XML, or binary files. FNT file open in Microsoft Notepad AngelCode Bitmap Font Generator (BFG) allows users to create bitmap fonts from TrueType fonts (.TTF files). The fonts BFG creates are saved as one or more raster images that contain the fonts characters and an FNT file. The FNT file contains data used to extract characters from the raster images. For example, each FNT file specifies characters IDs, X and Y coordinates within an associated image, widths, heights, and offsets. When creating a font, users can choose in what format the fonts FNT file should be saved. By default, BFG saves FNT files as plain text files. However, users can also choose to save FNT files as XML or binary files. If your FNT file is a plain text or XML file, you can open it in Microsoft Notepad (Windows) or any other text editor to view the font metadata it contains. If your FNT file is a binary file, it is not meant to be opened. Mac Apple TextEdit Included with OS. Any text editor Windows AngelCode Bitmap Font Generator. Microsoft Notepad Included with OS. Any text editor Linux Vim. Any text editor.",
    "Mac FontForge. Windows VSoft FontEdit. FontForge. Microsoft Windows. Linux FontForge. Mac Apple TextEdit Included with OS. Any text editor. Windows AngelCode Bitmap Font Generator. Microsoft Notepad Included with OS. Any text editor. Linux Vim. Any text editor.",
    "?"],
    ["font_files",
    ".VFB",
    "FontLab Studio Font File",
    "4.0",
    "Font file created by FontLab Studio, a font authoring program; contains a designed font, which includes the glyphs that make up the alphabet and other symbols; stores the font in a vector format so that the glyphs can be scaled without losing quality. When done editing fonts in FontLab Studio, you can export them to.TTF,.OTF,.PFB, and.PFA formats. Select File → Generate Font.. from the application menu. VFB files can be opened by several FontLab products, including FontLab Studio, Fontographer, TypeTool, AsiaFont Studio, TransType Pro, and others. Windows FontLab Studio. FontLab Fontographer —  (Discontinued). Trial FontLab TypeTool —  (Discontinued). Trial FontLab TransType Pro.",
    "Windows FontLab Studio. FontLab Fontographer —  (Discontinued). Trial FontLab TypeTool —  (Discontinued). Trial FontLab TransType Pro.",
    "?"],
    ["font_files",
    ".PFA",
    "Printer Font ASCII File",
    "4.0",
    "Adobe Type 1 font containing outlines of characters within the font; formatted in ASCII text (a human-readable format); should be stored in the system Fonts folder. Windows FontForge. Mac FontForge. Linux FontForgeFree.",
    "Windows FontForge. Mac FontForge. Linux FontForge.",
    "?"],
    ["font_files",
    ".ETX",
    "TeX Font Encoding File",
    "4.0",
    "Font file used by TeX and LaTeX typesetting systems; saved in a plain text format and contains markup that describes how a font is encoded for its appearance; allows font customization for TeX documents. Windows MiKTeX. TeXworks. Texmaker. Mac TeXworks. Texmaker. Linux TeXworks. TexmakerFree. ASCII text file format known as Setext that is used to distribute information over the Internet; can be opened with EasyView or another Setext viewer; may also be readable with a basic text editor, though the text formatting will be lost. Windows EasyView Mac EasyView.",
    "Windows MiKTeX. TeXworks. Texmaker. Mac TeXworks. Texmaker. Linux TeXworks. Texmaker. Windows EasyView. Mac EasyView.",
    "?"],
    ["font_files",
    ".WOFF",
    "Web Open Font Format File",
    "4.0",
    "A WOFF file is a web font file created in the WOFF (Web Open Font Format) format, an open format used for delivering webpage fonts on the fly. It is saved as a compressed container and supports TrueType (.TTF) and OpenType (.OTF) fonts and also supports font licensing information. WOFF files allow web developers to use custom fonts rather than the standard web fonts. Many browsers support the WOFF format, but most of them do not support WOFF files until recent versions. WOFF files are referenced within CSS files using the @font-face rule. WOFF files were replaced with.WOFF2 files, which are saved in the WOFF 2.0 format that features improved compression. NOTE: FontForge allows you to create OTF and TTF font files from the WOFF file. Windows FontForge. FontExplorer X Pro. Mac FontForge. FontExplorer X Pro. Linux FontForgeFree.",
    "Windows FontForge. FontExplorer X Pro. Mac FontForge. FontExplorer X Pro. Linux FontForge.",
    "?"],
    ["font_files",
    ".SFD",
    "Spline Font Database",
    "3.9",
    "Video file used by video games made for Sega Dreamcast, Nintendo GameCube, Microsoft Xbox, and other video game console systems; saves video in an uncommon Sofdec format that is not playable on standard video players; used for playing video game cinematic sequences. SFD files can be converted to.MPG files using a utility called sfd2mpg, which is part of the SFD Tool Pack by SWAT. However, this utility was not widely distributed and no longer is under development. SFD files can be created using Segas Movie Creator application, but it is also no longer being developed and was last released in 1999. The SFD Tool Pack by SWAT includes this program. NOTE: Pro Evolution Soccer 2012 (PES 2012) SFD files can be converted to the.MPG format using the discontinued PES Video & Audio Converter. Windows File Viewer Plus. VideoLAN VLC media player. Media Player Classic. Mac VideoLAN VLC media player. Linux VideoLAN VLC media playerFree. An SFD file is a font file saved in the Spline Font Database (SFD) format, the native format of FontForge. It contains ASCII text that describes a fonts name, version, and included characters, as well as other data. When opened in FontForge, SFD files appear as a grid of letters, numbers, and other font characters. SFD file open in FontForge FontForge is a free, multiplatform app that allows users to create, edit, and convert fonts. By default, FontForge saves fonts in its native SFD format (when a user selects File → Save.) Each SFD file contains a variety of metadata about the font it describes, specified in the files header. For example, each SFD file specifies its included fonts name, font family, weight, copyright information, version, layer count, display size, and default display layer. The file then goes on to describe each of the fonts characters, in entries that begin with StartChar and end with EndChar. You can open an SFD file with FontForge (multiplatform). To do so: Open FontForges Open Font window (either by opening the app or selecting File → Open). Set the Filter: field to FontForges SFD. Navigate to and open your SFD file. You can also open an SFD file with Microsoft Notepad (Windows), Apple TextEdit (Mac), or any other text editor, to view the ASCII data it contains. Windows FontForge. Any text editor Mac FontForge. Any text editor Linux FontForge. Any text editor. An SFD file contains a music score created by MagicScore Maestro, a music composition and notation program. It stores a composition, which may include instruments, time and key signatures, and music notes. SFD files also contain metadata, such as the title and composer of the score and the page layout of the score composition. SFD file open in MagicScore Maestro 8 You can open SFD files in Windows using MagicScore Maestro. To open an SFD file, select File → Open, navigate to the location of the file, and click Open. To create an SFD file using MagicScore Maestro, select File → New, compose the score, then select File → Save or Save as.. SFD files are the main file type used by MagicScore Maestro to save scores. However, you can also save scores as.MIDI files, Karaoke.KAR files, and Music.XML files by choosing the file types from the Save As dropdown menu. You can also export scores in MagicScore Maestro to an image, audio, or.PDF file by selecting File → Export. Windows MagicScore Maestro.",
    "Windows File Viewer Plus. VideoLAN VLC media player. Media Player Classic. Mac VideoLAN VLC media player. Linux VideoLAN VLC media player. Windows FontForge. Any text editor. Mac FontForge. Any text editor. Linux FontForge. Any text editor. Windows MagicScore Maestro.",
    "You can use FontForge (multiplatform) to convert SFD files to the following font formats:.TTF - TrueType Font.TTC - TrueType Font Collection.OTF - OpenType Font.UFO - Unified Font Object.DFONT - Mac OS X Data Fork Font.FNT - Windows Font File.WOFF - Web Open Font Format.PFA - Printer Font ASCII.PFB - Printer Font Binary."],
    ["font_files",
    ".PFB",
    "Printer Font Binary File",
    "3.9",
    "Adobe Type 1 font for Windows; similar to a.PFA file, but has been encoded in binary format; requires the associated.PFM file as well; both the PFB and PFM files should be stored within the system Fonts folder in order to be active. In addition to storing system fonts, PFB files are also used by AutoCAD for creating compiled.SHX font files. Windows CorelDRAW Graphics Suite 2023. FontForge. Autodesk AutoCAD 2023. Mac FontForge. Linux FontForgeFree.",
    "Windows CorelDRAW Graphics Suite 2023. FontForge. Autodesk AutoCAD 2023. Mac FontForge. Linux FontForge.",
    "?"],
    ["font_files",
    ".FOT",
    "Font Resource File",
    "3.9",
    "Font file used by Windows and applications that support TrueType fonts (.TTF files); contains font information and is used to install and configure an associated TrueType font; often used by application installers when installing fonts. FOT files are used in the process of installing embedded fonts in Windows. Embedded fonts allow fonts to be transferred between computers and require a FOT font resource file in addition to the TrueType font. The FOT file contains the information that Windows needs to recognize and install the font. The Windows API includes a function called CreateScalableFontResource that can be used for creating FOT files. Windows Microsoft Windows.",
    "Windows Microsoft Windows.",
    "?"],
    ["font_files",
    ".OTF",
    "OpenType Font",
    "3.8",
    "An OTF file is a font saved in the OpenType format developed by Microsoft and Adobe. The OpenType format combines aspects of the PostScript (.PS) and TrueType (.TTF) font formats. OTF fonts are fully scalable, meaning their characters can be resized without losing quality. OTF file open in Microsoft Windows Font Viewer In the 1990s, Microsoft set out to produce a competitor to Apples TrueType font format. In collaboration with Adobe, Microsoft produced the OpenType font, or OTF, format. The OpenType format is similar to the TrueType format, except that it includes additional data structures that determine how fonts appear and behave. In the early 2000s, the OpenType format became an open font standard. Thus, most computer systems can now recognize and install OTF fonts. How do I use an OTF file as a font? To use an OTF file as a font, you must first install it on your system. In Windows, you install fonts by placing them in the C:/​Windows/​Fonts directory. In macOS, you install fonts by opening them in Apple Font Book and selecting the Install Font button. You can open an OTF file in Microsoft Windows Font Viewer (Windows) or Apple Font Book (Mac). Before opening an OTF file in Windows Font Viewer, you must place the file in the C:/​Windows/​Fonts directory. Otherwise, Windows will not recognize the file as a valid font file. Can I install OTF fonts on my Android device? While it is more difficult to install an OTF font on an Android device than a Windows or Mac PC, you can do so. iFont is one application that allows users to install and use OTF fonts on Android devices. Windows Microsoft Windows Font Viewer Included with OS. FontForge. Mac Apple Font Book Included with OS. FontForge. Linux FontForge. Android iFontFree. Template for creating formulas used by OpenOffice spreadsheets; allows cells within the spreadsheet to be automatically filled in based on formula calculations; formatted using the OASIS OpenDocument XML standard. NOTE: The Organization for the Advancement of Structured Information Standards (OASIS) maintains the OpenDocument standard. Windows OpenOffice Calc. Mac OpenOffice Calc. Linux OpenOffice CalcFree. General interface format for creating tuft designs that can be processed by tufting machines; allows designs to be weaved into various textile products; contains information such as thread-up, yarn placement, and yarn tuft lengths. The OTF file format is specified in a Windows.INI file-like structure. NOTE: The OTF format is supported by NedGraphics tuft design software, but NedGraphics changed the .otf extension to .otu since there were conflicts with OpenType font files. Windows NedGraphics Tuft software.",
    "Windows Microsoft Windows Font Viewer Included with OS. FontForge. Mac Apple Font Book Included with OS. FontForge. Linux FontForge. Android iFont. Windows OpenOffice Calc. Mac OpenOffice Calc. Linux OpenOffice Calc. Windows NedGraphics Tuft software.",
    "?"],
    ["font_files",
    ".TTF",
    "TrueType Font",
    "3.8",
    "A TTF file is a font that can be installed in macOS, Windows, and other platforms. It is saved in the TrueType font format, which was created by Apple. TrueType fonts can be resized to any size without losing quality and look the same when printed as they do on the screen. TTF file open in Apple Font Book Apple developed and released the TrueType font format in the 1980s. Since its release, the TrueType format has become one of the most common formats used in both macOS and Windows. Most modern fonts that you find on your PC or online are saved in the TTF format. However, you may also encounter fonts saved in the.OTF (OpenType) format. How do I use a TTF file as a font? To use a TTF file as a font, you must first install it on your system: In Windows, you install fonts by placing them in the C:/​Windows/​Fonts directory. In macOS, you install fonts by opening them in Apple Font Book and selecting the Install Font button. In iOS and Android, you can use third-party apps, such as iFont, to install fonts. (Note that while they share the same name, the iOS and Android versions of iFont are developed by different developers.). You can open a TTF file in Microsoft Windows Font Viewer (Windows), Apple Font Book (Mac), or iFont (iOS, Android). Before opening a TTF file in Windows Font Viewer, you must place the file in the C:/​Windows/​Fonts directory. Otherwise, Windows will not recognize the file as a valid font file. Web File Helper. Windows File Viewer Plus — Get it from Microsoft. Microsoft Windows Font Viewer Included with OS. CorelDRAW Graphics Suite 2023. FontForge. FontExplorer X Pro. Mac Apple Font Book Included with OS. FontForge. FontExplorer X Pro. Linux FontForge. iOS iFont. Android iFontFree.",
    "Web File Helper. Windows File Viewer Plus — Get it from Microsoft. Microsoft Windows Font Viewer Included with OS. CorelDRAW Graphics Suite 2023. FontForge. FontExplorer X Pro. Mac Apple Font Book Included with OS. FontForge. FontExplorer X Pro. Linux FontForge. iOS iFont. Android iFont.",
    "?"],
    ["font_files",
    ".GXF",
    "General CADD Pro Font File",
    "3.8",
    "Font file used by General CADD Pro, a CAD design tool for Windows; stores a font that can be used to insert text and other symbols into a CAD drawing; must be available to the software in order for a CAD drawing that uses the font to be displayed properly. Windows General CADD Pro. General eXchange format used to transfer audiovisual clips between television program storage systems; may contain video, audio, time code, and metadata. The GXF format was originally developed for the interchange of camera shots over data networks and storing archives on data type. As technology has progressed, the container format has evolved to support MPEG, M-JPEG, and DV-based video compression, as well as audio, time code, and other user data. It is now a Society of motion Picture & Television Engineers (SMPTE) standard. Windows File Viewer Plus — Get it from Microsoft. VideoLAN VLC media player. Mac VideoLAN VLC media player. Linux VideoLAN VLC media playerFree.",
    "Windows General CADD Pro. Windows File Viewer Plus — Get it from Microsoft. VideoLAN VLC media player. Mac VideoLAN VLC media player. Linux VideoLAN VLC media player.",
    "?"],
    ["font_files",
    ".WOFF2",
    "Web Open Font Format 2.0 File",
    "3.7",
    "A WOFF2 file is a web font file created in the WOFF (Web Open Font Format) 2.0 format, an open format used to deliver webpage fonts on the fly. It is saved as a compressed container that supports TrueType (.TTF) and OpenType (.OTF) fonts. WOFF2 files also support font licensing metadata. The WOFF 2.0 format is similar to the WOFF 1.0 format but features improved compression in order to decrease network bandwidth use. The format is based on the Brotli compression algorithm, which is an open source data compression library used to increase the speed of web browsing. WOFF2 files are roughly 30% smaller than.WOFF files. WOFF2 files allow web developers to use custom fonts rather than the standard web fonts. Many browsers support the WOFF format, including Chrome (beginning in version 36), Edge (beginning in version 14), Firefox (beginning in version 35), Safari (beginning in version 10), and Opera (beginning in version 26). NOTE: WOFF2 files are referenced within CSS files using the @font-face rule. Windows FontExplorer X Pro. Mac FontExplorer X Pro.",
    "Windows FontExplorer X Pro. Mac FontExplorer X Pro.",
    "?"],
    ["font_files",
    ".ODTTF",
    "Obfuscated OpenType Font",
    "3.7",
    "Font file format used in the XML Paper Specification.XPS file and Microsoft Office 2007 formats; stores an obfuscated OpenType font that is based on the fonts used in the original document. The ODTFF format is an embedded font format, which means that it is included inside an electronic document, such as a.PDF or.DOCX file. It is mainly used as a resource in XPS files. However, the format uses the subsetted font, which means only the characters that are used in the document layout are included in the font file. Windows Microsoft XPS Viewer Included with OS. Pagemark XpsViewer Pagemark XpsConvert. Mozilla Firefox with Pagemark XpsPlugin. XPS Annotator —  (Discontinued). NiXPS View. NiXPS Edit. Mac Pagemark XpsViewer Apple Safari with Pagemark XpsPlugin Included with OS. Mozilla Firefox with Pagemark XpsPlugin. NiXPS View. NiXPS Edit. Linux Pagemark XpsViewer Mozilla Firefox with Pagemark XpsPlugin. KDE OkularFree.",
    "Windows Microsoft XPS Viewer Included with OS. Pagemark XpsViewer Pagemark XpsConvert. Mozilla Firefox with Pagemark XpsPlugin. XPS Annotator —  (Discontinued). NiXPS View. NiXPS Edit. Mac Pagemark XpsViewer Apple Safari with Pagemark XpsPlugin Included with OS. Mozilla Firefox with Pagemark XpsPlugin. NiXPS View. NiXPS Edit. Linux Pagemark XpsViewer Mozilla Firefox with Pagemark XpsPlugin. KDE Okular.",
    "?"],
    ["font_files",
    ".PMT",
    "PageMaker Template File",
    "3.7",
    "A PMT file is a template created for PageMaker 7.0, a page layout designing and formatting application. It contains a template of a character set referenced to identify key strokes for ASCII characters. PMT files are created for each version of PageMaker. PageMakers PMT files can be found in the Extras folder in the PageMaker folder. Examples of keystroke and character data held in a PMT character set: 0169 - © 0214 - Ö 0188 - 1⁄4 PageMaker was originally introduced in 1985 by Aldus but acquired in 1994 by Adobe. In 2004, Adobe stopped development of PageMaker replaced the program with InDesign. The Mac version of PageMaker will only run on OS 9 or earlier whereas the Windows version of PageMaker will run on XP or earlier. NOTE: PMT files replaced.T65 PageMaker files. charset.pmt - The common filename of the character set referenced by PageMaker 7.0 to identify keystroke functions. Windows Adobe PageMaker. Adobe InDesign 2023. Mac Adobe PageMaker. Adobe InDesign 2023.",
    "Windows Adobe PageMaker. Adobe InDesign 2023. Mac Adobe PageMaker. Adobe InDesign 2023.",
    "?"],
    ["font_files",
    ".GLIF",
    "Glyph Interchange Format File",
    "3.7",
    "A GLIF file is a file saved in the Glyph Interchange Format (GLIF) used for defining font symbols. It contains a glyph, which includes the name, format version, glyph width, and the X & Y point coordinates that define the outline of the symbol. GLIF files are saved in XML format. GLIF files are commonly found in.UFO files to store information about each glyph within the UFO font set. The files are located inside the glyphs folder in the UFO file. GLIF files typically are not removed from UFO files and are accessed when a program opens the UFO file, such as FontForge, RoboFont, or Glyphs. However, since GLIF files are saved in an XML format, they can be opened by a plain text editor. Windows FontForge. Mac Glyphs. FontForge. RoboFont. Linux FontForgeFree.",
    "Windows FontForge. Mac Glyphs. FontForge. RoboFont. Linux FontForge.",
    "?"],
    ["font_files",
    ".BF",
    "Birdfont Project File",
    "3.7",
    "Game data archive format used by games developed by Cryo Interactive Entertainment; contains game data, such as objects, maps, sounds, and music in a single archive. Microïds acquired Cryo Interactive in 2008, but several Microïds games still use the CryoBF format. The following games use BF files to store game data: Nostradamus: The Last Prophecy Safecracker: The Ultimate Puzzle Adventure Destination: Treasure Island Return to Mysterious Island Return to Mysterious Island 2: Minas Fate The Secret of the Nautilus Dracula 3: The Path of the Dragon BF files are referenced by the games above and are not meant to be opened manually. However, the contents of a BF file can be extracted using an unpacking program like Unpakke. Windows XpoZeds UnpakkeFree. A BF file is a source code file written in the Brainf*ck programming language. It contains a program that is meant to be compiled using a Brainf*ck compiler. BF files contain only the characters <, >, +, -,., ,, [, and ], as well as development comments. In 1992, Urban Müller created the Brainf*ck programming language. When creating Brainf*ck, Müllers goal was to create a language that could be compiled using the smallest-possible compiler. As such, the language includes only eight commands, each of which is implemented using a single character. These characters include: < > + -. , [ ] While the Brainf*ck language is quite impractical, some other developers have latched onto the esoteric language and its structure. When these developers create Brainf*ck programs, they typically save them in BF files. An example Brainf*ck program, saved within a BF file, might look like this: ++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>→>+[<]<-]>>.>---.+++++++.+++.>>.<-.<.+++.------.--------.>>+.>++. NOTE: Brainf*ck source code is also saved using the.B extension. Because BF files are plain text files, you can open and examine them using any text editor, such as Microsoft Notepad (Windows), Apple TextEdit (Mac), or Github Atom (cross-platform). If you want to run the Brainf*ck program a BF file contains, you can do so using a Brainf*ck development environment or interpreter, such as Brainf*ck Interpreter (Web, Android). Mac Apple TextEdit Included with OS. Github Atom —  (Discontinued). Microsoft Visual Studio Code. Any text editor Windows bfbuilder. Microsoft Notepad Included with OS. Github Atom —  (Discontinued). Microsoft Visual Studio Code. Any text editor Linux Vim. Github Atom —  (Discontinued). Microsoft Visual Studio Code. Any text editor Web Brainf*ck Interpreter. Android Brainf*ck Interpreter. Chrome OS Google Chrome Text Included with OS. A BF file is a custom font project file created by BirdFont. It contains XML-formatted text that describes a custom font. BF files are used to export fonts in common font formats, such as.TTF,.OTF,.EOT, and.SVG. BF file open in Birdfont Birdfont is a font design program that allows users to create, import, and edit fonts. The program is available in both free and commercial versions, which contain many but not all of the same features. For example, the free version of Birdfont can export only fonts created under the SIL Open Font License. When a Birdfont user saves an in-progress font design project, the project is saved as a BF file. BF files are XML files, meaning they contain plain text that is organized using an XML schema and elements. This text describes the font the user has created in Birdfont. For example, the <collection> element denotes the beginning of a new font character description. However, when opened in Birdfont, BF files do not appear as XML files. Instead, they appear as font stylesheets that a user can interact with and edit graphically, instead of via text. You can open a BF file in Birdfont (cross-platform). To do so, select Birdfonts sandwich menu (located in the programs upper right-hand corner), select File → Open, and then navigate to and open your BF file. The font your file describes will appear in Birdfonts Overview window. How do I convert a BF file into a TTF, OTF, EOT, or SVG file? To export a BF file as a TTF, OTF, EOT, or SVG file, open the file in the paid version of Birdfont and select the sandwich menu. Then, select Import and Export → Export Fonts. Mac Birdfont. Windows Birdfont. Linux Birdfont. A BF file is a game data archive saved in the BigFile format, which is used by games developed by Ubisoft that use the LyN or Jade engine. It contains the majority of the data for the game, which may include objects, skins, maps, sounds, movies, and music. Some games that utilize the LyN or Jade engines are The Adventures of Tintin: The Game, Rabbids Go Home, From Dust, Just Dance 2, ZombiU, and Prince of Persia: The Sands of Time. BF files are not meant to be manually opened. Instead, they are referenced by the game to load gameplay content. However, users looking to modify the content in BF game archives can use custom scripts with QuickBMS to extract the contents in a BF archive. Windows QuickBMSFree.",
    "Windows XpoZeds Unpakke. Mac Apple TextEdit Included with OS. Github Atom —  (Discontinued). Microsoft Visual Studio Code. Any text editor. Windows bfbuilder. Microsoft Notepad Included with OS. Github Atom —  (Discontinued). Microsoft Visual Studio Code. Any text editor. Linux Vim. Github Atom —  (Discontinued). Microsoft Visual Studio Code. Any text editor. Web Brainf*ck Interpreter. Android Brainf*ck Interpreter. Chrome OS Google Chrome Text Included with OS. Mac Birdfont. Windows Birdfont. Linux Birdfont. Windows QuickBMS.",
    "?"],
    ["font_files",
    ".TTC",
    "TrueType Font Collection",
    "3.7",
    "Collection of fonts saved in the TrueType (.TTF) format; used to deliver multiple fonts in a single file; useful for combining fonts that share many glyphs in common. TTC files allow multiple fonts to share glyph sets, which reduces the overall disk space required by the fonts. TrueType Font Collections are most often used for East Asian languages, such as Japanese and Korean. Windows Microsoft Windows Font Viewer Included with OS. ApoliSoft Font Fitting Room. FontForge. Mac Apple Font Book Included with OS. FontForge. Linux FontForgeFree.",
    "Windows Microsoft Windows Font Viewer Included with OS. ApoliSoft Font Fitting Room. FontForge. Mac Apple Font Book Included with OS. FontForge. Linux FontForge.",
    "?"],
    ["font_files",
    ".CHR",
    "Borland Character Set File",
    "3.6",
    "A CHR file is a game file used by Doki Doki Literature Club!, a visual Anime novel for Windows, macOS, and Linux. It stores Easter egg information that is referenced by the game. The name of the file, which may be monika.chr, natsuki.chr, sayori.chr, or yuri.chr (characters in the game) indicates the Easter egg content stored in the file. You will most likely only come across the Doki Doki Literature Club! CHR files if you have installed the visual novel. The CHR files are located in the characters folder in the game folder. The game does not actually open the various CHR files stored in the characters folder. Instead, it checks if the files are present, which triggers specific events in the visual novel. Each CHR file stores different information and can be opened with a program that supports the information contained in the file. For example, the monika.chr file is actually a.PNG file that can be opened with an image editor that supports PNG files. monika.chr - Name of the Monika character file that is actually a PNG file. natsuki.chr - Name of the Natsuki character file that is actually a.JPEG file. sayori.chr - Name of the Sayori character file that is actually an.OGG file. yuri.chr - Name of the Yuri character file that contains Base64-encoded text that is a short story about a teenage girl. Windows Team Salvato Doki Doki Literature Club!. Mac Team Salvato Doki Doki Literature Club!. Linux Team Salvato Doki Doki Literature Club!Free. 3D model file created by the CryENGINE SDK, a suite of applications used to build cross platform games for PC and console systems; includes the mesh, skeleton position, vertex properties, and morph targets; used for creating human and alien characters, as well as modeled game objects. Windows Crytek CryENGINE SDK. Provides style options for different fonts; may include different sizes and styles for a specific typeface; should be stored in the system Fonts folder. Windows Used by any program that can access system fonts. Three-dimensional character model created by 3ds Max, an application used for 3D modeling, rendering, and animation; contains the model of a still or animated character, including the geometry, textures, lighting effects, and other 3D model properties; used for developing characters that are published in games, movies, and television. 3ds Max can save CHR files as.MAX files. It can also export CHR files to several formats, including.DAE,.FXB,.DXF,.IGS,.STL, and many others. Windows Autodesk 3ds Max 2023.",
    "Windows Team Salvato Doki Doki Literature Club!. Mac Team Salvato Doki Doki Literature Club!. Linux Team Salvato Doki Doki Literature Club!. Windows Crytek CryENGINE SDK. Windows Used by any program that can access system fonts. Windows Autodesk 3ds Max 2023.",
    "?"],
    ["font_files",
    ".BDF",
    "Glyph Bitmap Distribution Format",
    "3.6",
    "Binary data format readable by forensic data analysis programs; used for identifying raw data recovered from blocks of unallocated space on a hard drive. BDF files are recognized by E-mail Detective, a forensic software program that can extract text and images from AOL email files. Windows Hot Pepper Technology E-mail Detective. Patch format used to update video game ROMs; may also be used to produce patches for binary files. Patching is commonly done to video game ROMs for one of two reasons. One reason is that the user wants to play a game in English that wasnt originally created for English users. The other reason is that the user wants to alter gameplay, such as the level order or character dialogue. The bsdiff/bspatch tools can be used to create and apply BDF patch files: To create a BDF patch file that makes your desired goodfile.123 from your original badfile.123, type bsdiff badfile.123 goodfile.123 patch.bdf. To apply a BDF patch file to your badfile.123, which subsequently creates your goodfile.123, type bspatch badfile.123 goodfile.123 patch.bdf. NOTE: The.BSDIFF file extension may also be used instead of the BDF extension but it is less common. Windows bsdiff/bspatch. Mac MultiPatch. bsdiff/bspatch. Linux bsdiff/bspatchFree. ASCII-based font format used on both Macintosh and Windows systems; stores Adobe screen fonts as human-readable data; must be placed in the system Fonts folder in order to be recognized by applications. BDF files are referenced by programs that access system fonts. Windows FontForge. Fontlab FONmaker —  (Discontinued). Mac FontForge. Linux FontForgeFree. Input file used by MSC Nastran, a program that analyzes structures such as aircraft, buildings, and spacecraft; contains bulk data definitions to be input into MSC Nastran to analyze the stress and strain levels of model structures; includes information such as the name of the bulk data, the number of grids, and the node locations of the elements that make up the models; data appears in the FORTRAN programming language, which was originally developed by IBM, and stands for Formula Translating System. BDF files are separated into 5 sections: Nastran Statement File Management Executive Control Case Control Bulk Data NOTE: The BDF file is similar to the.NAS and.DAT files, which are used to input data by MSC Nastran. Windows MSC Nastran. pynastran. Linux MSC Nastran. Disk image format used by ESO-MIDAS ( European Southern Observatory-Munich Image Data Analysis System) software; used primarily for storing astronomy data, such as stellar and surface photometry. Can be read and analyzed on Unix and Open VMS systems using ESO-MIDAS software. Linux ESO-MIDASFree.",
    "Windows Hot Pepper Technology E-mail Detective. Windows bsdiff/bspatch. Mac MultiPatch. bsdiff/bspatch. Linux bsdiff/bspatch. Windows FontForge. Fontlab FONmaker —  (Discontinued). Mac FontForge. Linux FontForge. Windows MSC Nastran. pynastran. Linux MSC Nastran. Linux ESO-MIDAS.",
    "?"],
    ["font_files",
    ".FON",
    "Windows Font Library",
    "3.6",
    "A FON file is a Windows 3.x font library file referenced by programs that access system fonts. It contains a number of fonts saved in the.FNT file format. FON files are now obsolete. FON files are.EXE files that have been renamed to use the.fon extension. Instead of containing an executable program, a FON file contains bitmapped or stroked fonts saved as FNT files. Various programs that use Windows fonts reference the default FON file included with the operating system. Notably, the fonts contained within a FON file cannot be resized like TrueType (.TTF) fonts. So, you may find several similar yet differently-sized fonts within a FON file. This is one of several reasons why TrueType fonts replaced FON- and FNT-based fonts. You can open a FON file in Microsoft Windows Font Viewer, which is included with Windows. To do so, simply make sure your FON file is located in the directory C:/​Windows/​Fonts and then double-click the file. As long as you have not changed FON files default file association, your file will open in Font Viewer. Windows Microsoft Windows Font Viewer Included with OS. Mac Cannot be opened Linux Cannot be opened.",
    "Windows Microsoft Windows Font Viewer Included with OS. Mac Cannot be opened. Linux Cannot be opened.",
    "?"],
    ["font_files",
    ".PFM",
    "Printer Font Metrics File",
    "3.5",
    "Adobe Type 1 font used by the Microsoft Windows operating system; includes measurements of characters within the font; requires an associated.PFB file for the font; does not contain the actual font glyphs, but helps the font in the PFB file to be displayed correctly. To install PFM/PFB fonts in Windows 7, you can copy the PFM and PFB files to the C:/​Windows/​Fonts/​ directory, right-click the PFM file, and select Install from the list. You can then view the font with the Microsoft Windows Font Viewer, which can be opened by navigating to the /​Windows/​Fonts/​ directory in the Windows Explorer, or by typing font in the Windows Start menu search box and then clicking View installed fonts from the populated search list. NOTE: If the PFB file is not in the same directory as the PFM file, it may be located in the /​PSFONTS/​ folder and the PFM file may be located in the /​PSFONTS/​PFM/​ folder. Windows Microsoft Windows Font Viewer Included with OS.",
    "Windows Microsoft Windows Font Viewer Included with OS.",
    "?"],
    ["font_files",
    ".FNT",
    "Bitmap Font Generator Font Descriptor",
    "3.5",
    "An FNT file is a font file used by the Windows operating system and often saved within the system fonts directory. It stores a generic font and may include vector and raster glyphs. FNT files have largely been replaced by TrueType (.TTF) and OpenType (.OTF) fonts. Mac FontForge. Windows VSoft FontEdit. FontForge. Microsoft Windows. Linux FontForgeFree. An FNT file is a bitmap font metadata file created by AngelCode Bitmap Font Generator. It contains data used to specify the fonts style and size, as well as extract the fonts characters from associated.DDS,.PNG. or.TGA files. FNT files can be plain text, XML, or binary files. FNT file open in Microsoft Notepad AngelCode Bitmap Font Generator (BFG) allows users to create bitmap fonts from TrueType fonts (.TTF files). The fonts BFG creates are saved as one or more raster images that contain the fonts characters and an FNT file. The FNT file contains data used to extract characters from the raster images. For example, each FNT file specifies characters IDs, X and Y coordinates within an associated image, widths, heights, and offsets. When creating a font, users can choose in what format the fonts FNT file should be saved. By default, BFG saves FNT files as plain text files. However, users can also choose to save FNT files as XML or binary files. If your FNT file is a plain text or XML file, you can open it in Microsoft Notepad (Windows) or any other text editor to view the font metadata it contains. If your FNT file is a binary file, it is not meant to be opened. Mac Apple TextEdit Included with OS. Any text editor Windows AngelCode Bitmap Font Generator. Microsoft Notepad Included with OS. Any text editor Linux Vim. Any text editor.",
    "Mac FontForge. Windows VSoft FontEdit. FontForge. Microsoft Windows. Linux FontForge. Mac Apple TextEdit Included with OS. Any text editor. Windows AngelCode Bitmap Font Generator. Microsoft Notepad Included with OS. Any text editor. Linux Vim. Any text editor.",
    "?"],
    ["font_files",
    ".BMFC",
    "Bitmap Font Configuration",
    "3.5",
    "A BMFC file contains settings used by AngelCode Bitmap Font Generator (BFG), a bitmap font creation app. Users can load the settings in BFG and use them to create a bitmap font. BMFC file open in AngelCode Bitmap Font Generator BFG allows users to create bitmap fonts from TrueType fonts (.TTF files). While doing so, users can specify many settings, including the fonts included characters, padding, spacing, and output file formats. Optionally, users can save their fonts settings in a BMFC file. This allows them to load and edit those settings at a later time, if they want to create a modified version of their font. BMFC files are plain text files that specify each of a fonts settings on separate lines. Settings are grouped by category, each of which begins with a #. BMFC file open in Microsoft Notepad BMFC files are meant to be opened in AngelCode Bitmap Font Generator (Windows). To open a BMFC file in BFG, select Options → Load configuration. Then, navigate to and open your BMFC file. You can also open a BMFC file in Microsoft Notepad (Windows) or any other text editor, to view the font configuration it contains. Windows AngelCode Bitmap Font Generator. Microsoft Notepad Included with OS. Any text editor Mac Apple TextEdit Included with OS. Any text editor Linux Vim. Any text editor.",
    "Windows AngelCode Bitmap Font Generator. Microsoft Notepad Included with OS. Any text editor. Mac Apple TextEdit Included with OS. Any text editor. Linux Vim. Any text editor.",
    "?"],
    ["font_files",
    ".AMFM",
    "Adobe Multiple Font Metrics File",
    "3.5",
    "Specifies the control data and global font information for a group of Adobe Font Metrics (.AFM) files; also includes one AFM file for each of the master designs in the font program; typically about 1.5KB in size. Windows Referenced by programs that support AFM fonts Mac Referenced by programs that support AFM fonts.",
    "Windows Referenced by programs that support AFM fonts. Mac Referenced by programs that support AFM fonts.",
    "?"],
    ["font_files",
    ".MF",
    "METAFONT File",
    "3.5",
    "An MF file is an archive used by games developed by Panda3D, a free 3D game engine. It contains game resource files, such as sound effects, texture, and models. MF files are compressed with Zip compression. MF files are created by the multify console program included with Panda3D, which can be used to store and extract files from an MF archive. The console program can also be used to encrypt the game resource files stored in the MF archive with a password. Games that use the MF archive include: Disneys Pirates of the Caribbean Online and Autumn Moon Entertainment/Crimson Cows A Vampyre Story. Panda3D is developed by Carnegie Mellon University. Mac Panda3D. Windows Panda3D. Linux Panda3DFree. Contains information about file packages in a Java archive (.JAR file); includes metadata about the archive such as what files it contains and what they are used for; included within the JAR file itself. Manifest files have the default pathname META-INF/MANIFEST.MF and are saved along with the JAR file. The default manifest file can be modified with a basic text editor. Mac Any text editor Windows Any text editor Linux Any text editor. Font file most commonly used by TeX and LaTeX typesetting systems; stores a font in a format that uses equations and fills to represent glyphs, rather than the outlining method used by TrueType and other fonts; requires a separate.TFM font metrics file to be typeset in a TeX document. Mac TeXworks. Windows MikTeX. TeXworksFree.",
    "Mac Panda3D. Windows Panda3D. Linux Panda3D. Mac Any text editor. Windows Any text editor. Linux Any text editor. Mac TeXworks. Windows MikTeX. TeXworks.",
    "?"],
    ["font_files",
    ".COMPOSITEFONT",
    "Windows Composite Font File",
    "3.4",
    "XML file used by Windows applications to display different fonts; contains definitions of font families and includes each font familys name, weight, style, underlining, and strikethrough setting; can be used to build multilingual fonts or to provide a fallback mechanism for specific characters that are missing on the system. COMPOSITEFONT files replace the Win32 mechanisms that were used to solve the problems of multilingual fonts, font fallback, font binding, font association, and end-user-defined characters (EUDC). Composite fonts can be accessed using the FontFamily and Typeface portions of the System.Windows.Media Windows Presentation Foundation (WPF) API. Composite font files can be created using a Windows software development IDE such as Microsoft Visual Studio. They can also be edited with a text editor since they are stored in an XML text format. Windows Microsoft Visual Studio 2022. Microsoft XML Notepad. Other text editor.",
    "Windows Microsoft Visual Studio 2022. Microsoft XML Notepad. Other text editor.",
    "?"],
    ["font_files",
    ".DFONT",
    "Mac OS X Data Fork Font",
    "3.3",
    "A DFONT file is a font used by Mac OS X (now macOS). It is a TrueType font saved in an OS X-specific format. In the past, some OS X system fonts were saved as DFONT files. DFONT file open in Apple Font Book Previous Macintosh operating systems allowed files to store data in two entities: the resource fork and the data fork. In Mac OS X, files can store data in only the data entity. To allow TrueType fonts that used the two-entity structure to continue working in OS X, Apple reformatted them to use the one-entity structure. These reformatted fonts are referred to as data fork TrueType fonts, or DFONT files. In the past, OS Xs Courier, Helvetica, Monaco, Symbol, Times, and ZapfDingbats fonts were all saved as DFONT files. These fonts have all since been deprecated, with some being replaced by typical TrueType font (.TTF) or OpenType font (.OTF) files. NOTE: Because DFONT files are saved in a Mac-specific file format, you cannot install them in Windows or Linux. You can open a DFONT file with Apple Font Book (Mac) or FontForge (multiplatform). To install the font a DFONT file contains, open it in Apple Font Book and select the Install Font button. You can use FontForge or DfontSplitter to convert DFONT files to other font formats. FontForge can convert DFONT files to the.TTF (TrueType font) or.OTF (OpenType font) format. DfontSplitter can convert DFONT files to the TTF format. Web File Helper. Windows File Viewer Plus — Get it from Microsoft. FontForge. DfontSplitter. Mac Apple Font Book Included with OS. DfontSplitter. Linux FontForgeFree.",
    "Web File Helper. Windows File Viewer Plus — Get it from Microsoft. FontForge. DfontSplitter. Mac Apple Font Book Included with OS. DfontSplitter. Linux FontForge.",
    "?"],
    ["font_files",
    ".GDR",
    "Symbian OS Font File",
    "3.3",
    "Font file used by Symbian OS devices, such as Nokia Series 60 smartphones; saves font characters in a bitmap format; can be transferred from a PC to the phone via Bluetooth or USB. GDR font files must be saved in the /System/Fonts directory on the Symbian device in order to function correctly. When a new font is installed, the device must be restarted to allow the Font and Bitmap server processes to recognize the font. Symbian OS programs, such as FileMan and FontRemover, can also be used to install or remove GDR files on the Symbian device. Windows FreeType Easy GDR Creator Linux FreeType.",
    "Windows FreeType Easy GDR Creator. Linux FreeType.",
    "?"],
    ["font_files",
    ".ABF",
    "Adobe Binary Screen Font File",
    "3.3",
    "Binary encoding of Adobes character bitmap distribution formation, which is an ASCII text-encoded font format; each ABF file consists of a sequence of 8-bit bytes; character bitmaps are stored in a strike format, which is a rectangular pixel array; the height of the rectangle is the height of the tallest character in the font and the width is the sum of all the character widths. The ABF format is also known as the Adobe Glyph Bitmap Distribution Format.. Windows Used by programs that access system fonts Mac Used by programs that access system fonts. Backup file created by Analysis Services, a component of Microsoft SQL Server used for online analytical processing (OLAP) and data mining; contains a backup of cubes, which are groups of metadata that specify dimensions, or a schema, for analyzing data that may reside in local or remote database locations; allows the analytics data to be restored or replicated. Windows Microsoft SQL Server 2019.",
    "Windows Used by programs that access system fonts. Mac Used by programs that access system fonts. Windows Microsoft SQL Server 2019.",
    "?"],
    ["font_files",
    ".PF2",
    "GRUB Font File",
    "3.3",
    "A PF2 file is a font file used by GNU GRUB (GRand Unified Bootloader), a multi-boot boot loader used for running multiple operating systems on the same computer. It is saved in the PF2 format, which is a simple and compact bitmap font format that supports Unicode. The PF2 format was developed in the late-2000s as an alternative to the BDF and PCF font formats. The format primarily improves upon the inefficient storage and multiple format variations of the BDF and PCF formats. PF2 files contain the font name, font family name, font weight, font slant, font point size. The files also store the maximum character pixel width and height and the pixel distance from the baseline of the font to the top and bottom of characters (ascent and descent). Linux GNU GRUBFree.",
    "Linux GNU GRUB.",
    "?"],
    ["font_files",
    ".PCF",
    "PaintCAD Font",
    "3.2",
    "Font format used by PaintCAD, a drawing program developed for Java-enabled mobile phones; contains a series of bitmap images for the characters in the font; used for typing text within PaintCAD. NOTE: PaintCAD is designed primarily for mobile devices. Since it is a Java program, it will only run on a computer if Java is installed. Windows PaintCAD. Mac PaintCAD. Linux PaintCADFree. File used by Valve Source, a game engine used for making first-person shooter games; stores a particle system that simulates smoke, fire, explosions, or another mass particle event; can be used for creating custom game modifications. The Valve Source development suite includes a tool called the Particle Editor, which can be used for viewing and editing PCF files. Windows Valve SourceFree. A PCF file contains the configuration of a client in a virtual private network (VPN) set up by Cisco Systems VPN Client software. It stores various information in.INI format, such as the username and password, along with the tunneling port and Domain Name System (DNS) settings. VPN Client software is primarily used by organizations that require a VPN for security purposes, such as businesses and universities. The software is installed on the various computers within the organization in order to connect to the VPN(s). When a user creates a new configuration in VPN Client and saves it, the application creates a PCF file to store the profile. PCF files are stored in the following directory: C:/​Program Files/​Cisco Systems/​VPN Client/​Profiles NOTE: Cisco Systems announced that it was discontinuing the VPN Client program in 2011 and officially dropped support in July 2014. You can open a PCF file with Cisco Systems VPN Client by selecting Connection entries → Profiles. Since PCF files are saved in the text INI format, you can also open a PCF file with a plain text editor. Windows Cisco Systems VPN Client Any text editor Mac Any text editor Linux Any text editor.",
    "Windows PaintCAD. Mac PaintCAD. Linux PaintCAD. Windows Valve Source. Windows Cisco Systems VPN Client Any text editor. Mac Any text editor. Linux Any text editor.",
    "?"],
    ["font_files",
    ".SFP",
    "Soft Font Printer File",
    "3.2",
    "Font file used by some printers; saves bitmap graphics that represent the glyphs of the font that can be printed; commonly named MICR.SFP and can be loaded on the printer using programs included with the printer purchase (examples include FLOAD.exe, HP Web Jetadmin utility, and TROY Printer Utility). With some printers, you can also store company logos and forms in the SFP files so they can be automatically printed on company documents. Windows HP Web Jetadmin software TROY Printer Utility.",
    "Windows HP Web Jetadmin software TROY Printer Utility.",
    "?"],
    ["font_files",
    ".MXF",
    "Maxis Font File",
    "3.1",
    "An MXF file is a video saved in the Material Exchange file format developed by The Society of Motion Picture and Television Engineers (SMPTE). It stores video and audio data and metadata that describes that data. MXF files often store television advertisements, television archives, and movies meant to be delivered to theaters. MXF file open in Apple QuickTime Player 10.5 The SMPTE created the MXF format to streamline video exchange between platforms, including video cameras, digital editing equipment, and servers. The format adopts a subset of the Advanced Authoring Format (AAF), which standardized the interchange of video between multiple vendors and platforms. Like any other media container format, the appropriate codec must be available to play the media an MXF file contains. You can open an MXF file with various video editors and media players, such as Adobe Premiere Pro (multiplatform), Avid Media Composer (multiplatform), Apple QuickTime Player (Mac), and VideoLAN VLC media player (multiplatform). To open an MXF file with VLC media player, select File → Open File... Windows File Viewer Plus. Adobe Premiere Pro 2023. Avid Media Composer. MAGIX VEGAS Pro 18. Grass Valley EDIUS. Avid Pro Tools. VideoLAN VLC media player. Aiseesoft MXF Converter. Mac Apple QuickTime Player Included with OS. Adobe Premiere Pro 2023. Avid Media Composer. Avid Pro Tools. VideoLAN VLC media player. Aiseesoft MXF Converter for Mac. Linux VideoLAN VLC media player. iOS PentaLoop PlayerXtreme Media Player. Font file used by Maxis SimCity 4, a life simulation game; stored in the /​Fonts/​ directory of the game installation and contains a font such as Arial, Courier, or another font; used for displaying game text. NOTE: Maxis is a subsidiary of Electronic Arts that develops SimCity games. Windows Electronic Arts SimCity 4.",
    "Windows File Viewer Plus. Adobe Premiere Pro 2023. Avid Media Composer. MAGIX VEGAS Pro 18. Grass Valley EDIUS. Avid Pro Tools. VideoLAN VLC media player. Aiseesoft MXF Converter. Mac Apple QuickTime Player Included with OS. Adobe Premiere Pro 2023. Avid Media Composer. Avid Pro Tools. VideoLAN VLC media player. Aiseesoft MXF Converter for Mac. Linux VideoLAN VLC media player. iOS PentaLoop PlayerXtreme Media Player. Windows Electronic Arts SimCity 4.",
    "Various media applications, including Adobe Premiere Pro, Avid Media Composer, and VideoLAN VLC media player, can convert MXF files to other formats. For example, Premiere Pro can convert MXF files to many file types, including the following formats:.MP4 - MPEG-4 Video.MOV - Apple QuickTime Movie.M4V - MPEG-4 iTunes Video.M2V - MPEG-2 Video.JPG - JPEG Image.PNG - Portable Network Graphic.DPX - Digital Picture Exchange.GIF - Graphical Interchange Format.EXR - OpenEXR Image.WAV - WAVE Audio.MP3 - MP3 Audio.AIF - Audio Interchange File Format.XML - Final Cut Pro XML."],
    ["font_files",
    ".GF",
    "METAFONT Bitmap File",
    "3.1",
    "Font file generated by TeX typesetting applications; saves the bitmap representation of a font that was originally in the equation-based METAFONT.MF format; used for generating glyphs (characters) into TeX documents as well as printing fonts for document proofs. GF files often have a corresponding.TFM file that contains size metadata for typesetting the font. Windows BaKoMa TeX. MikTeX. TeXworks. Mac TeXworksFree.",
    "Windows BaKoMa TeX. MikTeX. TeXworks. Mac TeXworks.",
    "?"],
    ["font_files",
    ".PFR",
    "Portable Font Resource File",
    "3.0",
    "Compact, platform-independent format for representing high-quality, scalable outline fonts; based on the TrueDoc PFR Specification developed by Bitstream, Inc; used for embedding rasterized fonts into Web pages and for displaying text on digital televisions. The PFR font format is used by several organizations that set digital TV standards. These organizations include ATDC, DAVIC, DVB, DTG, MHP, and OCAP. Windows Bitstream Font Fusion or TrueDoc. Image used by Paint Shop Pro, a graphics editor now known as PaintShop Photo Pro; stores a custom or preset picture frame graphic; can be used as a border for one or more images. NOTE: PFR files are not supported by the newer PaintShop Photo Pro. Windows Corel PaintShop Pro 2023.",
    "Windows Bitstream Font Fusion or TrueDoc. Windows Corel PaintShop Pro 2023.",
    "?"],
    ["font_files",
    ".XFN",
    "Ventura Printer Font",
    "3.0",
    "Printer font file used by the Corel Ventura publishing application, a program that can transform complex documents and XML files into visually rich publications; the XFN font format ensures accurate printing of text and is supported by Xerox printers. NOTE: Corel Ventura is no longer developed. Windows Corel Ventura —  (Discontinued).",
    "Windows Corel Ventura —  (Discontinued).",
    "?"],
    ["font_files",
    ".UFO",
    "Unified Font Object File",
    "3.0",
    "A UFO file is a raster image primarily created by Ulead PhotoImpact (now Corel PhotoImpact), but also recognized by other photo and video editing applications developed by Ulead. It may include multiple editing layers, similar to a Photoshop (.PSD) document. UFO files can be opened by Ulead Photo Explorer, but multi-layer images may not appear correctly. NOTE: Ulead was acquired by Corel, and PhotoImpact is now discontinued. Windows Corel PhotoImpact Ulead Photo Explorer. Binary Soft UniView. A UFO file is a file saved in the Unified Font Object (UFO) format. It contains data about a font, which includes the format version, creator, glyph layers, kerning information, images, and metadata. UFO file open in Glyphs 2.4 You can create UFO files to store a font using Glyphs or RoboFont, which are font editors for macOS. You can also open and edit UFO files using Glyphs and RoboFont in macOS, or FontForge, which is available for Windows, macOS, and Linux. UFO files are actually archives that store numerous files, which contain the font data. The files that can be found in a UFO file include.PLIST,.GLIF,.FEA, and.PNG files. The first version of the UFO format was originally published in 2004 but is rarely used anymore. The second version was published in 2009 and is the most common version used. The third version was published in 2012 but is not as widely adopted as the second version. The format was developed and is maintained by Tal Leming, Justin van Rossum, and Erik van Blokland. Windows FontForge. Mac Glyphs. FontForge. RoboFont. Linux FontForgeFree.",
    "Windows Corel PhotoImpact Ulead Photo Explorer. Binary Soft UniView. Windows FontForge. Mac Glyphs. FontForge. RoboFont. Linux FontForge.",
    "?"],
    ["font_files",
    ".TFM",
    "TeX Font Metric File",
    "3.0",
    "Font file created for typesetting fonts in TeX and LaTeX documents; does not contain the font glyphs (characters) themselves, but contains information about a font, such as the height and width of the glyphs; required by TeX typesetting and allows a font in a separate file to be typeset in a TeX document. TFM files can be generated from TrueType (.TTF) fonts using ttf2tfm. They can also be generated from Adobe Font Metric (.AFM) files using afm2tfm. Both programs are included in many TeX and LaTeX bundles. Other font formats are also used with TFM files, such as METAFONT (.MF) files. Mac TeXworks. Windows MiKTeX. TeXworksFree.",
    "Mac TeXworks. Windows MiKTeX. TeXworks.",
    "?"],
    ["font_files",
    ".VNF",
    "Vision Numeric Font",
    "3.0",
    "Single line font format used by Type3 software for direct engravings; also known as a stroke line font, which is directly machinable with the adequate equipment; developed for the Type3 Artistic Software family range in 1990. Windows Vision Numeric Type3 Software.",
    "Windows Vision Numeric Type3 Software.",
    "?"],
    ["font_files",
    ".AFM",
    "Adobe Font Metrics File",
    "2.9",
    "ASCII text-based font format developed by Adobe; stores font metric data for a Type 1 PostScript file; contains the master design of a specific font, which defines the way each character of the font looks. Mac Referenced by programs that use system fonts Windows Referenced by programs that use system fonts. Metadata file created in the Advanced Forensics Format (AFF), a file format used to save disk image data for digital evidence; saves only the metadata that was extracted out of an.AFF disk image file; allows the metadata to be separated from the raw disk image data. AFM files reference the AFF disk image data. When opened, the supporting program automatically locates the disk image data in the separate files and loads it appropriately. Windows AFFLIB —  (Discontinued). PassMark OSForensics. Linux AFFLIB —  (Discontinued).",
    "Mac Referenced by programs that use system fonts. Windows Referenced by programs that use system fonts. Windows AFFLIB —  (Discontinued). PassMark OSForensics. Linux AFFLIB —  (Discontinued).",
    "?"],
    ["font_files",
    ".TTE",
    "Private Character Editor File",
    "2.9",
    "Font file created by Private Character Editor, a program in Windows that allows users to make their own font characters; saves font information for a character set; can be used in conjunction with the Windows Character Map program to type custom characters. When you create custom characters, Private Character editor saves both a .tte file and a .euf file. Both are used when re-editing the character set. NOTE: The Private Character Editor program, eudcedit.exe, is located in the C:/​Windows/​System32/​ directory. EUDC.tte - The file containing custom font information for characters edited in Private Character Editor. Windows Microsoft Private Character Editor.",
    "Windows Microsoft Private Character Editor.",
    "?"],
    ["font_files",
    ".XFT",
    "ChiWriter Printer Font",
    "2.8",
    "24-pin printer font used by ChiWriter, a scientific multi-font word processor developed for MS-DOS and discontinued in 1996; formatted for 24-pin matrix printers. Windows Horstmann Software Design ChiWriterFree. Form created by Adobe Form Designer 5 or by the older version of the software called FormFlow Designer 99, also known as Accelio Capture FormFlow Designer. FormFlow was originally developed by JetForm Corporation, which became Accelio, and then was purchased by Adobe Systems. Adobe released a new version of the software called Adobe LiveCycle. Windows Adobe LiveCycle ES4.",
    "Windows Horstmann Software Design ChiWriter. Windows Adobe LiveCycle ES4.",
    "?"],
    ["font_files",
    ".EOT",
    "Embedded OpenType Font",
    "2.8",
    "An EOT file is an OpenType (.OTF) font meant to be embedded in a document, such as a webpage or PowerPoint presentation. EOT files are typically created and embedded using Microsoft Web Embedding Fonts Tool (WEFT). They are saved along with the associated document and not meant to be opened manually. Microsoft created the EOT file format to allow web developers to embed OpenType fonts in webpages, so text would always appear in the correct font online. Developers could use WEFT to transform an existing OpenType font file into an EOT file, which they would then link with one or more webpages. EOT files were compressed, making them faster to load over the web, and included some copyright-protection features, such as subsetting (including only a webpages needed characters) and encryption. Internet Explorer is the only browser that ever supported EOT files. EOT files have largely been replaced by.WOFF files, which are web-optimized font files. Microsoft stopped offering WEFT for download in 2019. NOTE: You can also create EOT files from.TTF files. EOT files are not meant to be opened. However, you can use eotinfo (cross-platform) to view information about an EOT file. Windows eotinfo. Mac eotinfo. Linux eotinfoFree.",
    "Windows eotinfo. Mac eotinfo. Linux eotinfo.",
    "?"],
    ["font_files",
    ".ACFM",
    "Adobe Composite Font Metrics File",
    "2.6",
    "Defines the structure of a composite font program; specifies the global metrics of the font program and the metrics of the immediate descendent font programs; metrics of individual characters in the font program are described within the associated.AFM file. ACFM files also specify the metrics for Original Composite Font (OCF) fonts. Windows Referenced by programs that support AFM fonts Mac Referenced by programs that support AFM fonts.",
    "Windows Referenced by programs that support AFM fonts. Mac Referenced by programs that support AFM fonts.",
    "?"],
    ["font_files",
    ".PK",
    "Packed METAFONT File",
    "2.4",
    "A PK file contains the visual representation of an audio waveform for a corresponding audio file. Audition and Cool Edit Pro automatically generate a PK file when a user imports a.WAV audio file and saves it in the same folder as the original audio file. Adobe replaced PK files with.PKF files when it released Audition version 4 (CS5.5). By default, peak files are generated for all audio files opened in Audition 2.0. This speeds up the waveform display process since the waveform only needs to be generated the first time. You may turn off the automatic peak file generation by choosing Edit → Preferences → Display, then deselecting Save Peak Cache Files. NOTE: Adobe acquired Syntrillium in May 2003 and rebranded the program Cool Edit Pro as Adobe Audition. Adobe Audition no longer supports PK files. If you need to open a PK file, you should attempt to open it with earlier versions of Audition (version 4 or earlier) or Cool Edit Pro. Windows Adobe Audition version 4 or earlier Syntrillium Cool Edit Pro Syntrillium Cool Edit 2000. Compressed font file created by GFtoPK, a program included with some TeX software distributions; contains the compressed copy of a.GF METAFONT bitmap font file and is used for maintaining smaller font sizes. Windows MikTeX. TeXworks. BaKoMa TeX. Mac TeXworksFree.",
    "Windows Adobe Audition version 4 or earlier Syntrillium Cool Edit Pro Syntrillium Cool Edit 2000. Windows MikTeX. TeXworks. BaKoMa TeX. Mac TeXworks.",
    "?"],
    ["font_files",
    ".SUIT",
    "Macintosh Font Suitcase",
    "2.3",
    "Font format used primarily by Mac OS Classic (Mac OS 9.2.2 and earlier); contains a single TrueType font or collection of fonts; should be stored in the System Folder/Fonts folder. SUIT files can be accessed by any program that uses system fonts. Mac Apple Mac OS Classic Included with OS.",
    "Mac Apple Mac OS Classic Included with OS.",
    "?"],
    ["font_files",
    ".FFIL",
    "Mac Font Suitcase",
    "2.3",
    "Collection of fonts used by Mac OS X; stored in a suitcase format than may contain multiple bitmap or TrueType fonts; should be stored in the System Fonts or user Fonts folder. NOTE: Mac OS X font suitcase files use FFIL as the file type info code. Some FFIL files may have a different file extension such as.DFONT. Mac Apple Font Book Included with OS.",
    "Mac Apple Font Book Included with OS.",
    "?"],
    ["font_files",
    ".NFTR",
    "Nintendo DS Font Type File",
    "2.3",
    "Font file used by some Nintendo DS games; stores multiple glyphs (characters) of the font using a bitmap grid for each character; used for displaying game text; can be edited with the program NFTRedit. Windows NFTReditFree.",
    "Windows NFTRedit.",
    "?"],
    ["font_files",
    ".EUF",
    "Private Character Editor File",
    "2.2",
    "File created by Microsoft Private Character Editor, an accessory program included with Windows; saves a font character set, which contains custom glyphs, or characters bitmaps, edited by the user; can be used in conjunction with Microsofts Character Map program to type custom characters in Windows. When you create new characters in Private Character Editor, the program uses two files, one with the .euf extension and one with the .tte extension. Both are used when loading and editing the character set. NOTE: Private Character Editor program, eudcedit.exe, is stored in the C:/​Windows/​System32/​ directory. EUDC.euf - The file containing the custom character bitmaps edited by the user in Private Character Editor. Windows Microsoft Private Character Editor.",
    "Windows Microsoft Private Character Editor.",
    "?"],
    ["font_files",
    ".TXF",
    "Celestia Font Texture File",
    "2.2",
    "Translation file created by Transit XV, a program used for language translation and localization; contains language terms and segments as well as their translations; stores a translation from a source.PXF file. TXF files are sent from a translator back to the project manager who supplied the original PXF file. They are stored in a compressed format. NOTE: TXF files can be converted from Transit NXT.TPF pack translation files in Transit XV. Windows STAR Group Transit. Standard text-based format for saving tax data, such as income and expenses; can be exported from financial software programs like Intuit Quicken or Microsoft Money and imported by tax preparation programs. Intuit publishes a file format specification and revision information for TXF files on their website. Windows Intuit TurboTax. Intuit Quicken. H&R Block Tax Software. Mac Intuit TurboTax. Intuit Quicken. H&R Block Tax Software. Font file used by Celestia, a universe simulation and visualization program; saves fonts in a format only used by Celestia; used for rendering OpenGL overlay text while visualizing scripted tours of the universe. TXF files can be generated from TrueType fonts (.TTF files) using a command line utility called ttf2txf. This tool is provided freely by the Celestia Development Team. NOTE: TXF files are stored in a fonts subdirectory within the Celestia installation. Windows Celestia. ttf2txf. Mac Celestia. ttf2txf. Linux Celestia. ttf2txfFree.",
    "Windows STAR Group Transit. Windows Intuit TurboTax. Intuit Quicken. H&R Block Tax Software. Mac Intuit TurboTax. Intuit Quicken. H&R Block Tax Software. Windows Celestia. ttf2txf. Mac Celestia. ttf2txf. Linux Celestia. ttf2txf.",
    "?"],
    ["font_files",
    ".MCF",
    "Watchtower Library Font File",
    "2.0",
    "An MCF file is a MARS component file, which will be used by Euclid Labs MARS. Euclid Labs plans to release MARS in early 2021. Windows Cannot be opened Mac Cannot be opened Linux Cannot be opened. File used by Watchtower Library, a program that allows users to browse a library of information provided by Jehovahs Witnesses; contains imported definitions for information such as fonts and languages. Windows Watchtower Library Mac Watchtower Library for Mac Linux Watchtower Library. An MCF file is a template file used by PEGASYS TMPGEnc, a discontinued video conversion application. It contains settings that TMPGEnc uses to convert videos from one format to another. TMPGEnc includes a default set of MCF files, and users can create their own MCF files. MCF file open in PEGASYS TMPGEnc PEGASYS TMPGEnc was a video encoding tool that could be used to convert videos to the MPEG-1 and MPEG-2 formats. The program included a number of encoding presets that users could select from to apply different settings to converted videos. These presets were saved as MCF files. Advanced TMPGEnc users could also create their own MCF files and use them as custom presets. To add a custom MCF file as a new template, users placed the file in TMPGEncs Template directory, typically located at C:/​Program Files/​Pegasys Inc/​TMPGEnc #.#/​Template. Users could also create custom MCF files directly in TMPGEnc, by adjusting a default template and clicking the Save button that appeared on the programs lower right-hand side. If you want to use an MCF file as a TMPGEnc template, place it in the programs Template directory. The template your MCF file contains will then appear in TMPGEncs template selection menu, accessible from the apps Load button. If necessary, you can edit custom MCF templates settings outside of TMPGEnc. (TMPGEncs default MCF files are read-only.) To do so, open your custom MCF file in any text editor, such as: Microsoft Notepad (Windows) Apple TextEdit (Mac) GitHub Atom (cross-platform) GNU Emacs (cross-platform). Windows PEGASYS TMPGEnc —  (Discontinued). PEGASYS TMPGEnc Plus —  (Discontinued). Trial Microsoft Notepad Included with OS. GitHub Atom —  (Discontinued). GNU Emacs. Any text editor Mac Apple TextEdit Included with OS. GitHub Atom —  (Discontinued). GNU Emacs. Any text editor Linux Vim. GitHub Atom —  (Discontinued). GNU Emacs. Any text editor Chrome OS Google Chrome Text Included with OS. File saved by MasterCook versions 2, 3, and 4, a program used store and manage recipes; contains cookbook data such as ingredients, directions, and other cooking information; used to save and load all recipes. MCF files can be converted into.MC2 files using MasterCook versions 5 and 6. Windows ValuSoft MasterCook.",
    "Windows Cannot be opened. Mac Cannot be opened. Linux Cannot be opened. Windows Watchtower Library. Mac Watchtower Library for Mac. Linux Watchtower Library. Windows PEGASYS TMPGEnc —  (Discontinued). PEGASYS TMPGEnc Plus —  (Discontinued). Trial Microsoft Notepad Included with OS. GitHub Atom —  (Discontinued). GNU Emacs. Any text editor. Mac Apple TextEdit Included with OS. GitHub Atom —  (Discontinued). GNU Emacs. Any text editor. Linux Vim. GitHub Atom —  (Discontinued). GNU Emacs. Any text editor. Chrome OS Google Chrome Text Included with OS. Windows ValuSoft MasterCook.",
    "?"],
    ["font_files",
    ".CHA",
    "Character Layout File",
    "2.0",
    "A CHA file is a settings file used by IRC clients such as mIRC. It contains the required information for opening an IRC channel, including the server, port, channel name, and potentially a password. When you double-click a CHA file, your IRC client will automatically open the associated channel. Windows mIRC. Visual IRC. XChat. Mac Snak. Custom color channel mixture that can be applied to a Photoshop image file; modifies the intensity of the source channels, such as red, green, and blue, and applies them to an output channel. Channel mixture presets can be loaded and saved by selecting Image→Adjustments→Channel Mixer from the Photoshop menu bar. Windows Adobe Photoshop 2023. Mac Adobe Photoshop 2023. Contains character layout information for a certain font; describes how the characters are positioned and defines the kerning between each character. CHA files can be opened and edited with DTL (Dutch Type Library) FontMaster software. Windows DTL OTMaster Light DTL FontMaster Light DTL KernMaster Mac DTL OTMaster Light Linux DTL OTMaster Light.",
    "Windows mIRC. Visual IRC. XChat. Mac Snak. Windows Adobe Photoshop 2023. Mac Adobe Photoshop 2023. Windows DTL OTMaster Light DTL FontMaster Light DTL KernMaster. Mac DTL OTMaster Light. Linux DTL OTMaster Light.",
    "?"],
    ["font_files",
    ".T65",
    "PageMaker Template File",
    "2.0",
    "A T65 file is a template created for PageMaker 6.0, a page layout designing and formatting application. It contains a character set template for identifying key strokes for ASCII characters available in most fonts. T65 files are referenced by each version of PageMaker 6.0 and earlier. T65 files can be found in your Extras folder in your PageMaker folder. Examples of keystroke and character data held in a T65 character set: 0172 - ¬ 0174 - ® CS+6 - § PageMaker was originally introduced in 1985 by Aldus but acquired in 1994 by Adobe. In 2004, Adobe stopped development of PageMaker replaced the program with InDesign. The Mac version of PageMaker will only run on OS 9 or earlier whereas the Windows version of PageMaker will run on XP or earlier. NOTE: T65 files were replaced by the.PMT PageMaker file in PageMaker 7.0. charset.t65 - The common filename of the character set referenced by PageMaker to identify keystroke functions. Windows Adobe PageMaker. Adobe InDesign 2023. Mac Adobe PageMaker. Adobe InDesign 2023.",
    "Windows Adobe PageMaker. Adobe InDesign 2023. Mac Adobe PageMaker. Adobe InDesign 2023.",
    "?"],
    ["font_files",
    ".YTF",
    "Google Picasa Font Cache",
    "1.8",
    "File contains font used by Google Picasa, an image sharing and editing program; holds the font type, size, and weight. Picasa enables the user to organize, edit, and share their photos. The user can share Picasa photo albums through Google+ with other users. Picasa also has an array of editing effects such as vignette, duo-tone, and borders. Arial-12-1.000000-400-0.ytf - common font and size used by Picasa. Mac Google Picasa —  (Discontinued). Windows Google Picasa —  (Discontinued).",
    "Mac Google Picasa —  (Discontinued). Windows Google Picasa —  (Discontinued).",
    "?"],
    ["font_files",
    ".LWFN",
    "Adobe Type 1 Mac Font File",
    "1.7",
    "Adobe PostScript font used on the Macintosh platform (Mac OS 9.x and earlier); contains the outline data of the font, similar to a.PFB file in Windows; used in combination with a FOND resource file and bitmap data. LWFN font files must be stored in the system Fonts folder in order to be active. In Mac OS 9, the fonts folder is located in /System Folder/Fonts. Mac Apple Mac OS Classic Included with OS.",
    "Mac Apple Mac OS Classic Included with OS.",
    "?"],
    ["font_files",
    ".F3F",
    "Crazy Machines Font File",
    "1.7",
    "Font file used by Crazy Machines, a physics-based puzzle game; saves font information that is used for rendering text within the game; saved within the /​data/​fonts/​ directory of the game installation. Windows Viva Media Crazy Machines.",
    "Windows Viva Media Crazy Machines.",
    "?"],
    ["font_files",
    ".FEA",
    "AFDKO Feature Definitions File",
    "1.0",
    "An FEA file is a data file commonly used in.UFO files to store font data. It contains Adobe Font Development Kit for OpenType (AFDKO) feature definitions, which may include language coverage, ligature, kerning, contour, and cursive information. FEA files are saved in plain text. FEA files are typically found in UFO files, along with.PLIST,.GLIF, and.PNG files. The files should not be removed from UFO files and are commonly accessed when a program, such as FontForge, RoboFont, or Glyphs, opens the UFO file. However, if you need to manually view an FEA file, you can open it in a text editor since it is saved in plain text. features.fea - The common name for the FEA file used in a UFO file. Windows FontForge. Mac Glyphs. FontForge. RoboFont. Linux FontForgeFree.",
    "Windows FontForge. Mac Glyphs. FontForge. RoboFont. Linux FontForge.",
    "?"],
    ["font_files",
    ".PFT",
    "ChiWriter Printer Font",
    "1.0",
    "A PFT file is a printer font used by Horstmann Software Design ChiWriter, a discontinued scientific document editor for MS-DOS. It contains data used to print a ChiWriter document (or a portion of a document) written in a certain font. PFT files can be opened and edited in ChiWriters font editor. Cay Horstmann created and released ChiWriter in 1986. The program was one of the first WYSIWYG editors that could write mathematical formulas. ChiWriter also gave users the ability to add superscripts and subscripts to their text. ChiWriter allowed users to write text and formulas using several different fonts. The printed versions of these fonts were saved as PFT files, while the displayed versions of these fonts were saved as.SFT files. If you still have access to ChiWriter (MS-DOS), you can open and edit your PFT file in the programs font editor. If you do not have access to ChiWriter, you may be able to use the Linux program Dosbox to run the version of ChiWriter linked below. Windows Horstmann Software Design ChiWriterFree.",
    "Windows Horstmann Software Design ChiWriter.",
    "?"],
    ["font_files",
    ".SFT",
    "ChiWriter Screen Font",
    "1.0",
    "File used by Microsoft Application Virtualization (App-V) Sequencer, a program used for deploying and updating applications within a Windows Enterprise environment; contains data required to deploy and configure a virtual application; used by system administrators when configuring virtual desktops for users. NOTE: App-V was formerly called SoftGrid before Microsoft acquired the software and renamed it. Windows Microsoft App-V Sequencer. An SFT file is an on-screen font used by Horstmann Software Design ChiWriter, a discontinued scientific document editor for MS-DOS. It contains data used to display a ChiWriter document (or a portion of a document) written in a certain font. SFT files can be opened and edited in ChiWriters font editor. Cay Horstmann created and released ChiWriter in 1986. The program was one of the first WYSIWYG editors that could write mathematical formulas. ChiWriter also gave users the ability to add superscripts and subscripts to their text. ChiWriter allowed users to write text and formulas using several different fonts. The displayed version of these fonts were saved as SFT files, while the displayed versions of these fonts were saved as.PFT files. If you still have access to ChiWriter, you can open and edit your SFT file in the programs font editor. If you do not have access to ChiWriter, you may be able to use the Linux program Dosbox to run the version of ChiWriter linked below. Windows Horstmann Software Design ChiWriterFree.",
    "Windows Microsoft App-V Sequencer. Windows Horstmann Software Design ChiWriter.",
    "?"],
]

